// Code generated by mockery v2.51.1. DO NOT EDIT.

package analysismanager

import mock "github.com/stretchr/testify/mock"

// MockanalysisRecordSaver is an autogenerated mock type for the analysisRecordSaver type
type MockanalysisRecordSaver struct {
	mock.Mock
}

type MockanalysisRecordSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockanalysisRecordSaver) EXPECT() *MockanalysisRecordSaver_Expecter {
	return &MockanalysisRecordSaver_Expecter{mock: &_m.Mock}
}

// createAnalysisRequest provides a mock function with given fields: analysisRequest
func (_m *MockanalysisRecordSaver) createAnalysisRequest(analysisRequest *AnalysisRequest) error {
	ret := _m.Called(analysisRequest)

	if len(ret) == 0 {
		panic("no return value specified for createAnalysisRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*AnalysisRequest) error); ok {
		r0 = rf(analysisRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockanalysisRecordSaver_createAnalysisRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'createAnalysisRequest'
type MockanalysisRecordSaver_createAnalysisRequest_Call struct {
	*mock.Call
}

// createAnalysisRequest is a helper method to define mock.On call
//   - analysisRequest *AnalysisRequest
func (_e *MockanalysisRecordSaver_Expecter) createAnalysisRequest(analysisRequest interface{}) *MockanalysisRecordSaver_createAnalysisRequest_Call {
	return &MockanalysisRecordSaver_createAnalysisRequest_Call{Call: _e.mock.On("createAnalysisRequest", analysisRequest)}
}

func (_c *MockanalysisRecordSaver_createAnalysisRequest_Call) Run(run func(analysisRequest *AnalysisRequest)) *MockanalysisRecordSaver_createAnalysisRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*AnalysisRequest))
	})
	return _c
}

func (_c *MockanalysisRecordSaver_createAnalysisRequest_Call) Return(_a0 error) *MockanalysisRecordSaver_createAnalysisRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockanalysisRecordSaver_createAnalysisRequest_Call) RunAndReturn(run func(*AnalysisRequest) error) *MockanalysisRecordSaver_createAnalysisRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockanalysisRecordSaver creates a new instance of MockanalysisRecordSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockanalysisRecordSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockanalysisRecordSaver {
	mock := &MockanalysisRecordSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
