quiet: False
with-expecter: True
filename: "mock_{{.InterfaceName | lower }}_test.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages:
  github.com/guardlight/server/internal/analysismanager:
    interfaces:
      analysisRequestStore:
      jobManagerRequester:
      subsriber:
      analysisStore:
      jobber:
      themeService:
      analysisGetter:
      sseEventSender:
  github.com/guardlight/server/internal/jobmanager:
    interfaces:
      jobStore:
  github.com/guardlight/server/internal/orchestrator:
    interfaces:
      jobManager:
      taskCreater:
      natsSender:
  github.com/guardlight/server/internal/theme:
    interfaces:
      themeStore: