analyzers:
    - concurrency: 4
      contextWindow: 16000
      description: Uses a basic word list to scan content for.
      external: true
      image: builtin
      inputs:
        - description: Words in this list will immediatly flag the content.
          key: strict_words
          name: Strict Words
          type: textarea
        - description: The threshold is the predefined value that triggers the analyzer to flag content when the value is reached or exceeded.
          key: threshold
          name: Threshold
          type: threshold
      key: word_search
      model: text
      name: Word Search
console:
    jwt:
        maxAge: 36000
        signingKey: qQJsN7FPjMUMGLzr8xRmBKGyYdRM81Go
cors:
    origin: http://192.168.178.142:4000
database:
    name: guardlight_test
    password: root
    port: 5432
    server: 127.0.0.1
    user: root
domain: 192.168.178.142
env: development
nats:
    password: bi7Y0YmHby5Hasfo2n0sOEuc9R1VxzND
    port: 4222
    server: ""
    user: gl_nats_user
orchestrator:
    scheduleRateCron: '* * * * * *'
parsers:
    - concurrency: 1
      description: Parses a text to an utf-8 formated text.
      external: true
      image: builtin
      name: Freetext
      type: freetext
    - concurrency: 1
      description: Parses a .epub file to an utf-8 formated text.
      external: true
      image: guardlight/parser-epub
      name: Epub
      type: epub
server:
    host: 0.0.0.0
    port: 6842
tz: UTC
users:
    - id: fc28fb4c-2280-49f5-a3ba-f99ed8f8843c
      password: a
      role: admin
      username: a
