analyzers:
    - concurrency: 4
      contextWindow: 16000
      description: Uses a basic word list to scan content for.
      external: true
      image: builtin
      inputs:
        - description: Words in this list will immediatly flag the content.
          key: strict_words
          name: Strict Words
          type: textarea
      key: word_search
      model: text
      name: Word Search
console:
    jwt:
        maxAge: 36000
        signingKey: qQJsN7FPjMUMGLzr8xRmBKGyYdRM81Go
cors:
    origin: http://192.168.178.142:4000
database:
    name: guardlight
    password: securePassword
    port: 5432
    server: 192.168.178.2
    user: guardlight
domain: 192.168.178.142
env: production
nats:
    password: bi7Y0YmHby5Hasfo2n0sOEuc9R1VxzND
    port: 4222
    server: ""
    user: gl_nats_user
orchestrator:
    scheduleRateCron: '* * * * * *'
parsers:
    - concurrency: 1
      description: Parses a text to an utf-8 formated text.
      external: true
      image: builtin
      key: freetext
      name: Freetext
      type: freetext
    - concurrency: 1
      description: Parses a .epub file to an utf-8 formated text.
      external: true
      image: guardlight/parser-epub
      key: epub
      name: Epub
      type: epub
reporters:
    - concurrency: 4
      description: This reporter will match the threshold to the amount of lines.
      external: true
      image: builtin
      key: word_count
      name: Word Count
server:
    host: 0.0.0.0
    port: 6842
tz: UTC
users:
    - apiKey: secretApiKey
      id: 6e145028-c854-459f-8e75-ad55e34359d9
      password: a
      role: admin
      username: a
