services:
    database:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=guardlight
            - POSTGRES_PASSWORD=securePassword
            - POSTGRES_DATABASE=guardlight

    server:
        image: ghcr.io/guardlight/server
        ports:
            - 6842:6842
        entrypoint:
            - GUARDLIGHT_DATABASE_USER=guardlight
            - GUARDLIGHT_DATABASE_PASSWORD=securePassword
            - GUARDLIGHT_DATABASE_NAME=guardlight
            - GUARDLIGHT_DATABASE_SERVER=<DATABASE_IP>
            - GUARDLIGHT_DATABASE_PORT=5432
            - GUARDLIGHT_CORS_ORIGIN=http://<CONSOLE_IP>:<CONSOLE_PORT>
            - GUARDLIGHT_DOMAIN=<SERVER_IP>
        depends_on:
            - database

    console:
        image: ghcr.io/guardlight/console
        environment:
            - GL_SERVER_URL=<SERVER_IP>:<SERVER_PORT>
        depends_on:
            - server
